// Generates src/data/approaches.ts from data-src/bga-data.json (see docs/DATA.md).
import fs from 'node:fs'

const raw = JSON.parse(fs.readFileSync(new URL('../data-src/bga-data.json', import.meta.url), 'utf8'))
const MODULE = {
  traffic: 'traffic', turns: 'turns', kerosene: 'kerosene', 'kerosene-leak': 'keroseneLeak',
  winds: 'winds', 'winds-headon': 'windsHeadon', 'real-time': 'realTime', intern: 'intern',
  'ice-brakes': 'iceBrakes', 'engine-loss': 'engineLoss',
}
const IGNORED = new Set(['special-abilities', 'modified-altitude'])
const BASE_TRACK_IDS = new Set([1,2,3,4,5,6,7,22,23,24,25,26,27,28,29,30,31,32,33,34,35].map(String))

const tracks = []
const seen = new Set()
const scenarios = []
for (const [id, t] of Object.entries(raw.tracks)) {
  const s = raw.scenarios[id]
  if (!s) continue
  const unsupported = s.modules.filter((m) => !(m in MODULE) && !IGNORED.has(m))
  if (unsupported.length) continue
  if (s.modules.some((m) => m === 'stuck-landing-gear')) continue
  const m = t.name.match(/^"([A-Z]+)"\s+(.*)$/)
  const code = m[1], airport = m[2]
  const spaces = []
  for (let i = 1; i <= t.size; i++) {
    const sp = t.spaces[String(i)] ?? {}
    const space = { planes: sp.plane ?? 0, trafficDice: sp.traffic ?? 0 }
    if (sp.allowedAxis) space.turns = sp.allowedAxis
    if (sp.alarm || sp.totalTrust) throw new Error('turbulence space in supported track ' + id)
    spaces.push(space)
  }
  const key = JSON.stringify([code, t.category, spaces, s.modules, s.nrOfSpecialAbilities ?? 0, s.altitude])
  if (seen.has(key)) continue
  seen.add(key)
  let sid = `${code.toLowerCase()}-${t.category}`
  if (tracks.some((x) => x.id === sid)) sid += `-${id}`
  tracks.push({ id: sid, code, airport, difficulty: t.category, size: t.size, spaces })
  scenarios.push({
    id: sid, trackId: sid, code, airport, difficulty: t.category,
    altitudeSide: s.altitude === '1' ? 'greenYellow' : 'redBlack',
    modules: s.modules.filter((x) => x in MODULE).map((x) => MODULE[x]),
    abilityCards: s.nrOfSpecialAbilities ?? 0,
    startFeet: s.modifiedAltitude ? 5000 : 6000,
    promo: !BASE_TRACK_IDS.has(id),
  })
}
const order = { green: 0, yellow: 1, red: 2, black: 3 }
scenarios.sort((a, b) => Number(a.promo) - Number(b.promo) || order[a.difficulty] - order[b.difficulty] || a.code.localeCompare(b.code))
const out = `// GENERATED by scripts/gen-data.mjs — do not edit. Provenance: docs/DATA.md
import type { ApproachTrack, Scenario } from './types'

export const TRACKS: ApproachTrack[] = ${JSON.stringify(tracks, null, 1)}

export const SCENARIOS: Scenario[] = ${JSON.stringify(scenarios, null, 1)}
`
fs.writeFileSync(new URL('../src/data/approaches.ts', import.meta.url), out)
console.log(tracks.length, 'tracks,', scenarios.filter((s) => !s.promo).length, 'base scenarios,', scenarios.filter((s) => s.promo).length, 'promo')
