// GENERATED by scripts/gen-data.mjs — do not edit. Provenance: docs/DATA.md
import type { ApproachTrack, Scenario } from './types'

export const TRACKS: ApproachTrack[] = [
 {
  "id": "yul-green",
  "code": "YUL",
  "airport": "Montreal-Trudeau",
  "difficulty": "green",
  "size": 7,
  "spaces": [
   {
    "planes": 0,
    "trafficDice": 0
   },
   {
    "planes": 0,
    "trafficDice": 0
   },
   {
    "planes": 1,
    "trafficDice": 0
   },
   {
    "planes": 2,
    "trafficDice": 0
   },
   {
    "planes": 1,
    "trafficDice": 0
   },
   {
    "planes": 3,
    "trafficDice": 0
   },
   {
    "planes": 2,
    "trafficDice": 0
   }
  ]
 },
 {
  "id": "hnd-green",
  "code": "HND",
  "airport": "Haneda",
  "difficulty": "green",
  "size": 8,
  "spaces": [
   {
    "planes": 0,
    "trafficDice": 2
   },
   {
    "planes": 1,
    "trafficDice": 0
   },
   {
    "planes": 1,
    "trafficDice": 0,
    "turns": [
     -1,
     0
    ]
   },
   {
    "planes": 2,
    "trafficDice": 0
   },
   {
    "planes": 1,
    "trafficDice": 0,
    "turns": [
     -2,
     -1
    ]
   },
   {
    "planes": 0,
    "trafficDice": 0,
    "turns": [
     -2,
     -1,
     0
    ]
   },
   {
    "planes": 2,
    "trafficDice": 0
   },
   {
    "planes": 1,
    "trafficDice": 0
   }
  ]
 },
 {
  "id": "kul-yellow",
  "code": "KUL",
  "airport": "Kuala Lumpur",
  "difficulty": "yellow",
  "size": 8,
  "spaces": [
   {
    "planes": 0,
    "trafficDice": 2
   },
   {
    "planes": 0,
    "trafficDice": 0,
    "turns": [
     1,
     2
    ]
   },
   {
    "planes": 1,
    "trafficDice": 0
   },
   {
    "planes": 1,
    "trafficDice": 1,
    "turns": [
     0,
     1
    ]
   },
   {
    "planes": 0,
    "trafficDice": 0,
    "turns": [
     1,
     2
    ]
   },
   {
    "planes": 1,
    "trafficDice": 0
   },
   {
    "planes": 1,
    "trafficDice": 0,
    "turns": [
     1,
     2
    ]
   },
   {
    "planes": 1,
    "trafficDice": 0
   }
  ]
 },
 {
  "id": "tgu-red",
  "code": "TGU",
  "airport": "Toncontin",
  "difficulty": "red",
  "size": 5,
  "spaces": [
   {
    "planes": 0,
    "trafficDice": 3
   },
   {
    "planes": 1,
    "trafficDice": 0,
    "turns": [
     -2,
     -1
    ]
   },
   {
    "planes": 1,
    "trafficDice": 2,
    "turns": [
     -1,
     0
    ]
   },
   {
    "planes": 1,
    "trafficDice": 0,
    "turns": [
     -2,
     -1
    ]
   },
   {
    "planes": 2,
    "trafficDice": 0
   }
  ]
 },
 {
  "id": "kul-black",
  "code": "KUL",
  "airport": "Kuala Lumpur",
  "difficulty": "black",
  "size": 8,
  "spaces": [
   {
    "planes": 0,
    "trafficDice": 3
   },
   {
    "planes": 0,
    "trafficDice": 0,
    "turns": [
     0,
     1
    ]
   },
   {
    "planes": 1,
    "trafficDice": 1
   },
   {
    "planes": 0,
    "trafficDice": 0,
    "turns": [
     -2
    ]
   },
   {
    "planes": 1,
    "trafficDice": 0,
    "turns": [
     -1,
     0
    ]
   },
   {
    "planes": 1,
    "trafficDice": 1,
    "turns": [
     0,
     1
    ]
   },
   {
    "planes": 1,
    "trafficDice": 0,
    "turns": [
     1,
     2
    ]
   },
   {
    "planes": 1,
    "trafficDice": 0
   }
  ]
 },
 {
  "id": "tgu-yellow",
  "code": "TGU",
  "airport": "Toncontin",
  "difficulty": "yellow",
  "size": 5,
  "spaces": [
   {
    "planes": 0,
    "trafficDice": 3
   },
   {
    "planes": 1,
    "trafficDice": 0,
    "turns": [
     -2,
     -1
    ]
   },
   {
    "planes": 1,
    "trafficDice": 0,
    "turns": [
     -1,
     0
    ]
   },
   {
    "planes": 1,
    "trafficDice": 0,
    "turns": [
     -2,
     -1
    ]
   },
   {
    "planes": 1,
    "trafficDice": 0
   }
  ]
 },
 {
  "id": "hnd-red",
  "code": "HND",
  "airport": "Haneda",
  "difficulty": "red",
  "size": 8,
  "spaces": [
   {
    "planes": 1,
    "trafficDice": 3
   },
   {
    "planes": 0,
    "trafficDice": 0,
    "turns": [
     -1,
     0
    ]
   },
   {
    "planes": 1,
    "trafficDice": 0
   },
   {
    "planes": 1,
    "trafficDice": 1,
    "turns": [
     -2,
     -1
    ]
   },
   {
    "planes": 1,
    "trafficDice": 1,
    "turns": [
     -1,
     0
    ]
   },
   {
    "planes": 2,
    "trafficDice": 1
   },
   {
    "planes": 1,
    "trafficDice": 0,
    "turns": [
     -2,
     -1
    ]
   },
   {
    "planes": 1,
    "trafficDice": 0
   }
  ]
 },
 {
  "id": "lga-black",
  "code": "LGA",
  "airport": "LaGuardia",
  "difficulty": "black",
  "size": 7,
  "spaces": [
   {
    "planes": 0,
    "trafficDice": 0,
    "turns": [
     0,
     1,
     2
    ]
   },
   {
    "planes": 0,
    "trafficDice": 0
   },
   {
    "planes": 0,
    "trafficDice": 1,
    "turns": [
     1,
     2
    ]
   },
   {
    "planes": 0,
    "trafficDice": 0
   },
   {
    "planes": 1,
    "trafficDice": 1,
    "turns": [
     -2,
     -1
    ]
   },
   {
    "planes": 1,
    "trafficDice": 0
   },
   {
    "planes": 0,
    "trafficDice": 0
   }
  ]
 },
 {
  "id": "lga-yellow",
  "code": "LGA",
  "airport": "LaGuardia",
  "difficulty": "yellow",
  "size": 7,
  "spaces": [
   {
    "planes": 0,
    "trafficDice": 1
   },
   {
    "planes": 0,
    "trafficDice": 0,
    "turns": [
     0,
     1,
     2
    ]
   },
   {
    "planes": 0,
    "trafficDice": 1
   },
   {
    "planes": 1,
    "trafficDice": 0,
    "turns": [
     -2,
     -1,
     0
    ]
   },
   {
    "planes": 2,
    "trafficDice": 1
   },
   {
    "planes": 1,
    "trafficDice": 0
   },
   {
    "planes": 1,
    "trafficDice": 0
   }
  ]
 },
 {
  "id": "dus-black",
  "code": "DUS",
  "airport": "Düsseldorf",
  "difficulty": "black",
  "size": 8,
  "spaces": [
   {
    "planes": 1,
    "trafficDice": 2
   },
   {
    "planes": 0,
    "trafficDice": 0,
    "turns": [
     0
    ]
   },
   {
    "planes": 0,
    "trafficDice": 1
   },
   {
    "planes": 1,
    "trafficDice": 2,
    "turns": [
     -2,
     -1
    ]
   },
   {
    "planes": 2,
    "trafficDice": 0
   },
   {
    "planes": 1,
    "trafficDice": 1,
    "turns": [
     1,
     2
    ]
   },
   {
    "planes": 3,
    "trafficDice": 0
   },
   {
    "planes": 2,
    "trafficDice": 0
   }
  ]
 },
 {
  "id": "dus-yellow",
  "code": "DUS",
  "airport": "Düsseldorf",
  "difficulty": "yellow",
  "size": 8,
  "spaces": [
   {
    "planes": 0,
    "trafficDice": 3
   },
   {
    "planes": 1,
    "trafficDice": 0
   },
   {
    "planes": 1,
    "trafficDice": 0
   },
   {
    "planes": 2,
    "trafficDice": 0,
    "turns": [
     -1,
     0,
     1
    ]
   },
   {
    "planes": 1,
    "trafficDice": 0
   },
   {
    "planes": 2,
    "trafficDice": 2,
    "turns": [
     -1,
     0,
     1
    ]
   },
   {
    "planes": 1,
    "trafficDice": 0
   },
   {
    "planes": 1,
    "trafficDice": 0
   }
  ]
 },
 {
  "id": "cdg-red",
  "code": "CDG",
  "airport": "Paris-Charles de Gaulle",
  "difficulty": "red",
  "size": 8,
  "spaces": [
   {
    "planes": 1,
    "trafficDice": 2
   },
   {
    "planes": 0,
    "trafficDice": 0
   },
   {
    "planes": 0,
    "trafficDice": 0
   },
   {
    "planes": 0,
    "trafficDice": 1,
    "turns": [
     -2,
     -1
    ]
   },
   {
    "planes": 1,
    "trafficDice": 0
   },
   {
    "planes": 1,
    "trafficDice": 1,
    "turns": [
     1,
     2
    ]
   },
   {
    "planes": 2,
    "trafficDice": 0
   },
   {
    "planes": 1,
    "trafficDice": 0
   }
  ]
 },
 {
  "id": "cdg-yellow",
  "code": "CDG",
  "airport": "Paris-Charles de Gaulle",
  "difficulty": "yellow",
  "size": 8,
  "spaces": [
   {
    "planes": 0,
    "trafficDice": 3
   },
   {
    "planes": 1,
    "trafficDice": 0
   },
   {
    "planes": 0,
    "trafficDice": 0
   },
   {
    "planes": 0,
    "trafficDice": 1
   },
   {
    "planes": 2,
    "trafficDice": 1
   },
   {
    "planes": 2,
    "trafficDice": 1
   },
   {
    "planes": 1,
    "trafficDice": 0
   },
   {
    "planes": 2,
    "trafficDice": 0
   }
  ]
 },
 {
  "id": "ter-yellow",
  "code": "TER",
  "airport": "Lajes, Açores",
  "difficulty": "yellow",
  "size": 7,
  "spaces": [
   {
    "planes": 0,
    "trafficDice": 3,
    "turns": [
     -2,
     -1
    ]
   },
   {
    "planes": 0,
    "trafficDice": 0,
    "turns": [
     0,
     1,
     2
    ]
   },
   {
    "planes": 0,
    "trafficDice": 0,
    "turns": [
     -2,
     -1
    ]
   },
   {
    "planes": 0,
    "trafficDice": 0,
    "turns": [
     1,
     2
    ]
   },
   {
    "planes": 1,
    "trafficDice": 0,
    "turns": [
     -2,
     -1
    ]
   },
   {
    "planes": 1,
    "trafficDice": 0,
    "turns": [
     1,
     2
    ]
   },
   {
    "planes": 1,
    "trafficDice": 0
   }
  ]
 },
 {
  "id": "ter-black",
  "code": "TER",
  "airport": "Lajes, Açores",
  "difficulty": "black",
  "size": 7,
  "spaces": [
   {
    "planes": 0,
    "trafficDice": 3,
    "turns": [
     -2,
     -1
    ]
   },
   {
    "planes": 0,
    "trafficDice": 0,
    "turns": [
     1,
     2
    ]
   },
   {
    "planes": 0,
    "trafficDice": 0,
    "turns": [
     -2,
     -1
    ]
   },
   {
    "planes": 1,
    "trafficDice": 0,
    "turns": [
     1,
     2
    ]
   },
   {
    "planes": 1,
    "trafficDice": 0,
    "turns": [
     -2,
     -1
    ]
   },
   {
    "planes": 1,
    "trafficDice": 0,
    "turns": [
     1,
     2
    ]
   },
   {
    "planes": 1,
    "trafficDice": 0
   }
  ]
 },
 {
  "id": "nzir-black",
  "code": "NZIR",
  "airport": "Ice Runway",
  "difficulty": "black",
  "size": 8,
  "spaces": [
   {
    "planes": 0,
    "trafficDice": 2
   },
   {
    "planes": 1,
    "trafficDice": 0
   },
   {
    "planes": 0,
    "trafficDice": 0,
    "turns": [
     -1,
     0
    ]
   },
   {
    "planes": 0,
    "trafficDice": 0
   },
   {
    "planes": 0,
    "trafficDice": 0,
    "turns": [
     1,
     2
    ]
   },
   {
    "planes": 0,
    "trafficDice": 0
   },
   {
    "planes": 0,
    "trafficDice": 0,
    "turns": [
     -1,
     0
    ]
   },
   {
    "planes": 0,
    "trafficDice": 0
   }
  ]
 },
 {
  "id": "nzir-red",
  "code": "NZIR",
  "airport": "Ice Runway",
  "difficulty": "red",
  "size": 8,
  "spaces": [
   {
    "planes": 0,
    "trafficDice": 3
   },
   {
    "planes": 0,
    "trafficDice": 0,
    "turns": [
     -2,
     -1
    ]
   },
   {
    "planes": 0,
    "trafficDice": 0
   },
   {
    "planes": 1,
    "trafficDice": 0
   },
   {
    "planes": 1,
    "trafficDice": 0,
    "turns": [
     0,
     1
    ]
   },
   {
    "planes": 1,
    "trafficDice": 0
   },
   {
    "planes": 0,
    "trafficDice": 0
   },
   {
    "planes": 0,
    "trafficDice": 0
   }
  ]
 },
 {
  "id": "bud-yellow",
  "code": "BUD",
  "airport": "Budapest Liszt Ferenc",
  "difficulty": "yellow",
  "size": 6,
  "spaces": [
   {
    "planes": 0,
    "trafficDice": 3
   },
   {
    "planes": 1,
    "trafficDice": 0
   },
   {
    "planes": 1,
    "trafficDice": 0,
    "turns": [
     0,
     1
    ]
   },
   {
    "planes": 2,
    "trafficDice": 1
   },
   {
    "planes": 1,
    "trafficDice": 0,
    "turns": [
     -2,
     -1
    ]
   },
   {
    "planes": 2,
    "trafficDice": 0
   }
  ]
 },
 {
  "id": "bud-red",
  "code": "BUD",
  "airport": "Budapest Liszt Ferenc",
  "difficulty": "red",
  "size": 6,
  "spaces": [
   {
    "planes": 1,
    "trafficDice": 4
   },
   {
    "planes": 1,
    "trafficDice": 0
   },
   {
    "planes": 1,
    "trafficDice": 1,
    "turns": [
     0,
     1
    ]
   },
   {
    "planes": 1,
    "trafficDice": 1,
    "turns": [
     1,
     2
    ]
   },
   {
    "planes": 1,
    "trafficDice": 0,
    "turns": [
     -2,
     -1
    ]
   },
   {
    "planes": 1,
    "trafficDice": 0
   }
  ]
 },
 {
  "id": "blq-red",
  "code": "BLQ",
  "airport": "Guglielmo Marconi",
  "difficulty": "red",
  "size": 6,
  "spaces": [
   {
    "planes": 1,
    "trafficDice": 3
   },
   {
    "planes": 1,
    "trafficDice": 0,
    "turns": [
     0
    ]
   },
   {
    "planes": 2,
    "trafficDice": 0
   },
   {
    "planes": 1,
    "trafficDice": 0,
    "turns": [
     0
    ]
   },
   {
    "planes": 1,
    "trafficDice": 0
   },
   {
    "planes": 2,
    "trafficDice": 0
   }
  ]
 },
 {
  "id": "blq-green",
  "code": "BLQ",
  "airport": "Guglielmo Marconi",
  "difficulty": "green",
  "size": 6,
  "spaces": [
   {
    "planes": 1,
    "trafficDice": 3
   },
   {
    "planes": 1,
    "trafficDice": 0,
    "turns": [
     -1,
     0
    ]
   },
   {
    "planes": 1,
    "trafficDice": 1
   },
   {
    "planes": 1,
    "trafficDice": 0,
    "turns": [
     0,
     1
    ]
   },
   {
    "planes": 2,
    "trafficDice": 0
   },
   {
    "planes": 2,
    "trafficDice": 0
   }
  ]
 },
 {
  "id": "atl-green",
  "code": "ATL",
  "airport": "Hartsfield-Jackson",
  "difficulty": "green",
  "size": 8,
  "spaces": [
   {
    "planes": 0,
    "trafficDice": 4
   },
   {
    "planes": 0,
    "trafficDice": 0
   },
   {
    "planes": 0,
    "trafficDice": 1
   },
   {
    "planes": 0,
    "trafficDice": 0
   },
   {
    "planes": 1,
    "trafficDice": 1
   },
   {
    "planes": 2,
    "trafficDice": 1
   },
   {
    "planes": 1,
    "trafficDice": 0
   },
   {
    "planes": 2,
    "trafficDice": 0
   }
  ]
 },
 {
  "id": "atl-yellow",
  "code": "ATL",
  "airport": "Hartsfield-Jackson",
  "difficulty": "yellow",
  "size": 8,
  "spaces": [
   {
    "planes": 0,
    "trafficDice": 1
   },
   {
    "planes": 1,
    "trafficDice": 1
   },
   {
    "planes": 0,
    "trafficDice": 0,
    "turns": [
     -1,
     0,
     1
    ]
   },
   {
    "planes": 2,
    "trafficDice": 2
   },
   {
    "planes": 2,
    "trafficDice": 1
   },
   {
    "planes": 1,
    "trafficDice": 0
   },
   {
    "planes": 3,
    "trafficDice": 0,
    "turns": [
     1,
     2
    ]
   },
   {
    "planes": 1,
    "trafficDice": 0
   }
  ]
 },
 {
  "id": "gig-yellow",
  "code": "GIG",
  "airport": "Galeão",
  "difficulty": "yellow",
  "size": 7,
  "spaces": [
   {
    "planes": 0,
    "trafficDice": 2
   },
   {
    "planes": 0,
    "trafficDice": 0
   },
   {
    "planes": 2,
    "trafficDice": 0
   },
   {
    "planes": 1,
    "trafficDice": 1
   },
   {
    "planes": 2,
    "trafficDice": 1
   },
   {
    "planes": 3,
    "trafficDice": 0
   },
   {
    "planes": 1,
    "trafficDice": 0
   }
  ]
 },
 {
  "id": "gig-red",
  "code": "GIG",
  "airport": "Galeão",
  "difficulty": "red",
  "size": 7,
  "spaces": [
   {
    "planes": 0,
    "trafficDice": 3
   },
   {
    "planes": 1,
    "trafficDice": 0
   },
   {
    "planes": 2,
    "trafficDice": 1
   },
   {
    "planes": 2,
    "trafficDice": 0
   },
   {
    "planes": 1,
    "trafficDice": 1
   },
   {
    "planes": 1,
    "trafficDice": 0
   },
   {
    "planes": 2,
    "trafficDice": 0
   }
  ]
 },
 {
  "id": "pbh-black",
  "code": "PBH",
  "airport": "Paro",
  "difficulty": "black",
  "size": 6,
  "spaces": [
   {
    "planes": 1,
    "trafficDice": 3
   },
   {
    "planes": 0,
    "trafficDice": 0
   },
   {
    "planes": 1,
    "trafficDice": 1,
    "turns": [
     -2,
     -1
    ]
   },
   {
    "planes": 1,
    "trafficDice": 1,
    "turns": [
     -2,
     -1
    ]
   },
   {
    "planes": 1,
    "trafficDice": 1,
    "turns": [
     2
    ]
   },
   {
    "planes": 1,
    "trafficDice": 0
   }
  ]
 },
 {
  "id": "pbh-red",
  "code": "PBH",
  "airport": "Paro",
  "difficulty": "red",
  "size": 6,
  "spaces": [
   {
    "planes": 0,
    "trafficDice": 3
   },
   {
    "planes": 1,
    "trafficDice": 0
   },
   {
    "planes": 1,
    "trafficDice": 0,
    "turns": [
     -2,
     -1
    ]
   },
   {
    "planes": 1,
    "trafficDice": 1,
    "turns": [
     -2,
     -1,
     0
    ]
   },
   {
    "planes": 1,
    "trafficDice": 0,
    "turns": [
     1,
     2
    ]
   },
   {
    "planes": 1,
    "trafficDice": 0
   }
  ]
 },
 {
  "id": "osl-red",
  "code": "OSL",
  "airport": "Gardermoen",
  "difficulty": "red",
  "size": 8,
  "spaces": [
   {
    "planes": 1,
    "trafficDice": 3
   },
   {
    "planes": 0,
    "trafficDice": 0
   },
   {
    "planes": 1,
    "trafficDice": 1
   },
   {
    "planes": 0,
    "trafficDice": 0
   },
   {
    "planes": 0,
    "trafficDice": 1
   },
   {
    "planes": 1,
    "trafficDice": 0
   },
   {
    "planes": 0,
    "trafficDice": 1
   },
   {
    "planes": 0,
    "trafficDice": 0
   }
  ]
 },
 {
  "id": "osl-green",
  "code": "OSL",
  "airport": "Gardermoen",
  "difficulty": "green",
  "size": 8,
  "spaces": [
   {
    "planes": 0,
    "trafficDice": 2
   },
   {
    "planes": 0,
    "trafficDice": 0
   },
   {
    "planes": 1,
    "trafficDice": 0
   },
   {
    "planes": 0,
    "trafficDice": 1
   },
   {
    "planes": 1,
    "trafficDice": 0
   },
   {
    "planes": 1,
    "trafficDice": 0
   },
   {
    "planes": 1,
    "trafficDice": 0
   },
   {
    "planes": 0,
    "trafficDice": 0
   }
  ]
 },
 {
  "id": "kef-black",
  "code": "KEF",
  "airport": "Keflavik",
  "difficulty": "black",
  "size": 6,
  "spaces": [
   {
    "planes": 0,
    "trafficDice": 2
   },
   {
    "planes": 0,
    "trafficDice": 0,
    "turns": [
     -2,
     -1,
     0
    ]
   },
   {
    "planes": 2,
    "trafficDice": 1
   },
   {
    "planes": 1,
    "trafficDice": 0,
    "turns": [
     0,
     1,
     2
    ]
   },
   {
    "planes": 1,
    "trafficDice": 0,
    "turns": [
     -1,
     0,
     1
    ]
   },
   {
    "planes": 0,
    "trafficDice": 0
   }
  ]
 },
 {
  "id": "kef-yellow",
  "code": "KEF",
  "airport": "Keflavik",
  "difficulty": "yellow",
  "size": 6,
  "spaces": [
   {
    "planes": 0,
    "trafficDice": 2
   },
   {
    "planes": 0,
    "trafficDice": 0
   },
   {
    "planes": 1,
    "trafficDice": 1
   },
   {
    "planes": 1,
    "trafficDice": 0
   },
   {
    "planes": 1,
    "trafficDice": 1
   },
   {
    "planes": 0,
    "trafficDice": 0
   }
  ]
 },
 {
  "id": "lhr-yellow",
  "code": "LHR",
  "airport": "Heathrow",
  "difficulty": "yellow",
  "size": 6,
  "spaces": [
   {
    "planes": 1,
    "trafficDice": 2
   },
   {
    "planes": 1,
    "trafficDice": 0
   },
   {
    "planes": 1,
    "trafficDice": 1
   },
   {
    "planes": 2,
    "trafficDice": 1
   },
   {
    "planes": 1,
    "trafficDice": 1
   },
   {
    "planes": 2,
    "trafficDice": 0
   }
  ]
 },
 {
  "id": "lhr-green",
  "code": "LHR",
  "airport": "Heathrow",
  "difficulty": "green",
  "size": 6,
  "spaces": [
   {
    "planes": 0,
    "trafficDice": 1
   },
   {
    "planes": 1,
    "trafficDice": 0
   },
   {
    "planes": 1,
    "trafficDice": 1
   },
   {
    "planes": 2,
    "trafficDice": 0
   },
   {
    "planes": 2,
    "trafficDice": 1
   },
   {
    "planes": 2,
    "trafficDice": 0
   }
  ]
 },
 {
  "id": "prg-yellow",
  "code": "PRG",
  "airport": "Václav Havel",
  "difficulty": "yellow",
  "size": 8,
  "spaces": [
   {
    "planes": 0,
    "trafficDice": 0
   },
   {
    "planes": 0,
    "trafficDice": 0
   },
   {
    "planes": 1,
    "trafficDice": 0
   },
   {
    "planes": 3,
    "trafficDice": 1
   },
   {
    "planes": 0,
    "trafficDice": 0
   },
   {
    "planes": 3,
    "trafficDice": 1
   },
   {
    "planes": 2,
    "trafficDice": 0
   },
   {
    "planes": 3,
    "trafficDice": 0
   }
  ]
 },
 {
  "id": "prg-green",
  "code": "PRG",
  "airport": "Václav Havel",
  "difficulty": "green",
  "size": 8,
  "spaces": [
   {
    "planes": 0,
    "trafficDice": 1
   },
   {
    "planes": 0,
    "trafficDice": 0,
    "turns": [
     -1,
     0
    ]
   },
   {
    "planes": 1,
    "trafficDice": 1
   },
   {
    "planes": 1,
    "trafficDice": 0,
    "turns": [
     1,
     2
    ]
   },
   {
    "planes": 0,
    "trafficDice": 0
   },
   {
    "planes": 1,
    "trafficDice": 1
   },
   {
    "planes": 1,
    "trafficDice": 0
   },
   {
    "planes": 1,
    "trafficDice": 0
   }
  ]
 },
 {
  "id": "ter-yellow-52",
  "code": "TER",
  "airport": "Lajes, Açores",
  "difficulty": "yellow",
  "size": 7,
  "spaces": [
   {
    "planes": 0,
    "trafficDice": 3,
    "turns": [
     -2,
     -1
    ]
   },
   {
    "planes": 0,
    "trafficDice": 0,
    "turns": [
     0,
     1,
     2
    ]
   },
   {
    "planes": 0,
    "trafficDice": 0,
    "turns": [
     -2,
     -1
    ]
   },
   {
    "planes": 0,
    "trafficDice": 0,
    "turns": [
     1,
     2
    ]
   },
   {
    "planes": 1,
    "trafficDice": 0,
    "turns": [
     -2,
     -1,
     0
    ]
   },
   {
    "planes": 1,
    "trafficDice": 0,
    "turns": [
     1,
     2
    ]
   },
   {
    "planes": 1,
    "trafficDice": 0
   }
  ]
 },
 {
  "id": "ter-black-53",
  "code": "TER",
  "airport": "Lajes, Açores",
  "difficulty": "black",
  "size": 7,
  "spaces": [
   {
    "planes": 0,
    "trafficDice": 4,
    "turns": [
     -2,
     -1
    ]
   },
   {
    "planes": 0,
    "trafficDice": 0,
    "turns": [
     1,
     2
    ]
   },
   {
    "planes": 0,
    "trafficDice": 0,
    "turns": [
     -2,
     -1
    ]
   },
   {
    "planes": 1,
    "trafficDice": 0,
    "turns": [
     1,
     2
    ]
   },
   {
    "planes": 1,
    "trafficDice": 0,
    "turns": [
     -2,
     -1
    ]
   },
   {
    "planes": 1,
    "trafficDice": 0,
    "turns": [
     1,
     2
    ]
   },
   {
    "planes": 1,
    "trafficDice": 0
   }
  ]
 },
 {
  "id": "mad-black",
  "code": "MAD",
  "airport": "Madrid–Barajas",
  "difficulty": "black",
  "size": 7,
  "spaces": [
   {
    "planes": 0,
    "trafficDice": 3,
    "turns": [
     1,
     2
    ]
   },
   {
    "planes": 0,
    "trafficDice": 0
   },
   {
    "planes": 0,
    "trafficDice": 1,
    "turns": [
     -1
    ]
   },
   {
    "planes": 1,
    "trafficDice": 0
   },
   {
    "planes": 1,
    "trafficDice": 0,
    "turns": [
     -2,
     -1
    ]
   },
   {
    "planes": 1,
    "trafficDice": 1
   },
   {
    "planes": 1,
    "trafficDice": 0
   }
  ]
 },
 {
  "id": "mad-yellow",
  "code": "MAD",
  "airport": "Madrid–Barajas",
  "difficulty": "yellow",
  "size": 7,
  "spaces": [
   {
    "planes": 0,
    "trafficDice": 4
   },
   {
    "planes": 1,
    "trafficDice": 0,
    "turns": [
     0,
     1
    ]
   },
   {
    "planes": 0,
    "trafficDice": 1,
    "turns": [
     -1,
     0
    ]
   },
   {
    "planes": 1,
    "trafficDice": 0
   },
   {
    "planes": 1,
    "trafficDice": 1,
    "turns": [
     -2,
     -1
    ]
   },
   {
    "planes": 1,
    "trafficDice": 0
   },
   {
    "planes": 2,
    "trafficDice": 0
   }
  ]
 }
]

export const SCENARIOS: Scenario[] = [
 {
  "id": "atl-green",
  "trackId": "atl-green",
  "code": "ATL",
  "airport": "Hartsfield-Jackson",
  "difficulty": "green",
  "altitudeSide": "greenYellow",
  "modules": [
   "traffic",
   "intern"
  ],
  "abilityCards": 0,
  "startFeet": 6000,
  "promo": false
 },
 {
  "id": "hnd-green",
  "trackId": "hnd-green",
  "code": "HND",
  "airport": "Haneda",
  "difficulty": "green",
  "altitudeSide": "greenYellow",
  "modules": [
   "traffic",
   "turns"
  ],
  "abilityCards": 0,
  "startFeet": 6000,
  "promo": false
 },
 {
  "id": "lhr-green",
  "trackId": "lhr-green",
  "code": "LHR",
  "airport": "Heathrow",
  "difficulty": "green",
  "altitudeSide": "greenYellow",
  "modules": [
   "traffic"
  ],
  "abilityCards": 0,
  "startFeet": 6000,
  "promo": false
 },
 {
  "id": "osl-green",
  "trackId": "osl-green",
  "code": "OSL",
  "airport": "Gardermoen",
  "difficulty": "green",
  "altitudeSide": "greenYellow",
  "modules": [
   "traffic",
   "kerosene"
  ],
  "abilityCards": 0,
  "startFeet": 6000,
  "promo": false
 },
 {
  "id": "prg-green",
  "trackId": "prg-green",
  "code": "PRG",
  "airport": "Václav Havel",
  "difficulty": "green",
  "altitudeSide": "greenYellow",
  "modules": [
   "traffic",
   "turns",
   "kerosene"
  ],
  "abilityCards": 2,
  "startFeet": 6000,
  "promo": false
 },
 {
  "id": "yul-green",
  "trackId": "yul-green",
  "code": "YUL",
  "airport": "Montreal-Trudeau",
  "difficulty": "green",
  "altitudeSide": "greenYellow",
  "modules": [],
  "abilityCards": 0,
  "startFeet": 6000,
  "promo": false
 },
 {
  "id": "atl-yellow",
  "trackId": "atl-yellow",
  "code": "ATL",
  "airport": "Hartsfield-Jackson",
  "difficulty": "yellow",
  "altitudeSide": "greenYellow",
  "modules": [
   "traffic",
   "turns",
   "keroseneLeak"
  ],
  "abilityCards": 1,
  "startFeet": 6000,
  "promo": false
 },
 {
  "id": "gig-yellow",
  "trackId": "gig-yellow",
  "code": "GIG",
  "airport": "Galeão",
  "difficulty": "yellow",
  "altitudeSide": "greenYellow",
  "modules": [
   "traffic",
   "winds"
  ],
  "abilityCards": 1,
  "startFeet": 6000,
  "promo": false
 },
 {
  "id": "kef-yellow",
  "trackId": "kef-yellow",
  "code": "KEF",
  "airport": "Keflavik",
  "difficulty": "yellow",
  "altitudeSide": "greenYellow",
  "modules": [
   "traffic",
   "iceBrakes"
  ],
  "abilityCards": 1,
  "startFeet": 6000,
  "promo": false
 },
 {
  "id": "kul-yellow",
  "trackId": "kul-yellow",
  "code": "KUL",
  "airport": "Kuala Lumpur",
  "difficulty": "yellow",
  "altitudeSide": "greenYellow",
  "modules": [
   "traffic",
   "turns",
   "kerosene"
  ],
  "abilityCards": 1,
  "startFeet": 6000,
  "promo": false
 },
 {
  "id": "lhr-yellow",
  "trackId": "lhr-yellow",
  "code": "LHR",
  "airport": "Heathrow",
  "difficulty": "yellow",
  "altitudeSide": "greenYellow",
  "modules": [
   "traffic",
   "intern"
  ],
  "abilityCards": 0,
  "startFeet": 6000,
  "promo": false
 },
 {
  "id": "prg-yellow",
  "trackId": "prg-yellow",
  "code": "PRG",
  "airport": "Václav Havel",
  "difficulty": "yellow",
  "altitudeSide": "greenYellow",
  "modules": [
   "traffic",
   "keroseneLeak"
  ],
  "abilityCards": 2,
  "startFeet": 6000,
  "promo": false
 },
 {
  "id": "tgu-yellow",
  "trackId": "tgu-yellow",
  "code": "TGU",
  "airport": "Toncontin",
  "difficulty": "yellow",
  "altitudeSide": "greenYellow",
  "modules": [
   "traffic",
   "turns",
   "kerosene"
  ],
  "abilityCards": 2,
  "startFeet": 6000,
  "promo": false
 },
 {
  "id": "gig-red",
  "trackId": "gig-red",
  "code": "GIG",
  "airport": "Galeão",
  "difficulty": "red",
  "altitudeSide": "redBlack",
  "modules": [
   "traffic",
   "winds",
   "keroseneLeak"
  ],
  "abilityCards": 2,
  "startFeet": 6000,
  "promo": false
 },
 {
  "id": "hnd-red",
  "trackId": "hnd-red",
  "code": "HND",
  "airport": "Haneda",
  "difficulty": "red",
  "altitudeSide": "redBlack",
  "modules": [
   "traffic",
   "turns",
   "kerosene",
   "intern"
  ],
  "abilityCards": 1,
  "startFeet": 6000,
  "promo": false
 },
 {
  "id": "osl-red",
  "trackId": "osl-red",
  "code": "OSL",
  "airport": "Gardermoen",
  "difficulty": "red",
  "altitudeSide": "redBlack",
  "modules": [
   "traffic",
   "keroseneLeak",
   "iceBrakes"
  ],
  "abilityCards": 2,
  "startFeet": 6000,
  "promo": false
 },
 {
  "id": "pbh-red",
  "trackId": "pbh-red",
  "code": "PBH",
  "airport": "Paro",
  "difficulty": "red",
  "altitudeSide": "redBlack",
  "modules": [
   "traffic",
   "turns",
   "kerosene",
   "realTime"
  ],
  "abilityCards": 2,
  "startFeet": 6000,
  "promo": false
 },
 {
  "id": "tgu-red",
  "trackId": "tgu-red",
  "code": "TGU",
  "airport": "Toncontin",
  "difficulty": "red",
  "altitudeSide": "redBlack",
  "modules": [
   "traffic",
   "turns",
   "kerosene",
   "winds"
  ],
  "abilityCards": 2,
  "startFeet": 6000,
  "promo": false
 },
 {
  "id": "kef-black",
  "trackId": "kef-black",
  "code": "KEF",
  "airport": "Keflavik",
  "difficulty": "black",
  "altitudeSide": "redBlack",
  "modules": [
   "traffic",
   "turns",
   "winds",
   "iceBrakes"
  ],
  "abilityCards": 2,
  "startFeet": 6000,
  "promo": false
 },
 {
  "id": "kul-black",
  "trackId": "kul-black",
  "code": "KUL",
  "airport": "Kuala Lumpur",
  "difficulty": "black",
  "altitudeSide": "redBlack",
  "modules": [
   "traffic",
   "turns",
   "kerosene",
   "realTime"
  ],
  "abilityCards": 2,
  "startFeet": 6000,
  "promo": false
 },
 {
  "id": "pbh-black",
  "trackId": "pbh-black",
  "code": "PBH",
  "airport": "Paro",
  "difficulty": "black",
  "altitudeSide": "redBlack",
  "modules": [
   "traffic",
   "turns",
   "kerosene",
   "realTime"
  ],
  "abilityCards": 2,
  "startFeet": 6000,
  "promo": false
 },
 {
  "id": "blq-green",
  "trackId": "blq-green",
  "code": "BLQ",
  "airport": "Guglielmo Marconi",
  "difficulty": "green",
  "altitudeSide": "greenYellow",
  "modules": [
   "traffic",
   "turns",
   "keroseneLeak"
  ],
  "abilityCards": 0,
  "startFeet": 6000,
  "promo": true
 },
 {
  "id": "bud-yellow",
  "trackId": "bud-yellow",
  "code": "BUD",
  "airport": "Budapest Liszt Ferenc",
  "difficulty": "yellow",
  "altitudeSide": "greenYellow",
  "modules": [
   "traffic",
   "turns",
   "winds"
  ],
  "abilityCards": 0,
  "startFeet": 6000,
  "promo": true
 },
 {
  "id": "cdg-yellow",
  "trackId": "cdg-yellow",
  "code": "CDG",
  "airport": "Paris-Charles de Gaulle",
  "difficulty": "yellow",
  "altitudeSide": "greenYellow",
  "modules": [
   "traffic",
   "winds",
   "intern"
  ],
  "abilityCards": 0,
  "startFeet": 6000,
  "promo": true
 },
 {
  "id": "dus-yellow",
  "trackId": "dus-yellow",
  "code": "DUS",
  "airport": "Düsseldorf",
  "difficulty": "yellow",
  "altitudeSide": "greenYellow",
  "modules": [
   "traffic",
   "turns",
   "keroseneLeak"
  ],
  "abilityCards": 2,
  "startFeet": 6000,
  "promo": true
 },
 {
  "id": "lga-yellow",
  "trackId": "lga-yellow",
  "code": "LGA",
  "airport": "LaGuardia",
  "difficulty": "yellow",
  "altitudeSide": "greenYellow",
  "modules": [
   "traffic",
   "turns",
   "iceBrakes"
  ],
  "abilityCards": 2,
  "startFeet": 6000,
  "promo": true
 },
 {
  "id": "mad-yellow",
  "trackId": "mad-yellow",
  "code": "MAD",
  "airport": "Madrid–Barajas",
  "difficulty": "yellow",
  "altitudeSide": "greenYellow",
  "modules": [
   "traffic",
   "turns",
   "intern"
  ],
  "abilityCards": 1,
  "startFeet": 5000,
  "promo": true
 },
 {
  "id": "ter-yellow",
  "trackId": "ter-yellow",
  "code": "TER",
  "airport": "Lajes, Açores",
  "difficulty": "yellow",
  "altitudeSide": "greenYellow",
  "modules": [
   "traffic",
   "turns",
   "iceBrakes",
   "engineLoss"
  ],
  "abilityCards": 2,
  "startFeet": 6000,
  "promo": true
 },
 {
  "id": "ter-yellow-52",
  "trackId": "ter-yellow-52",
  "code": "TER",
  "airport": "Lajes, Açores",
  "difficulty": "yellow",
  "altitudeSide": "greenYellow",
  "modules": [
   "traffic",
   "turns",
   "iceBrakes",
   "engineLoss"
  ],
  "abilityCards": 2,
  "startFeet": 6000,
  "promo": true
 },
 {
  "id": "blq-red",
  "trackId": "blq-red",
  "code": "BLQ",
  "airport": "Guglielmo Marconi",
  "difficulty": "red",
  "altitudeSide": "redBlack",
  "modules": [
   "traffic",
   "turns",
   "kerosene"
  ],
  "abilityCards": 1,
  "startFeet": 6000,
  "promo": true
 },
 {
  "id": "bud-red",
  "trackId": "bud-red",
  "code": "BUD",
  "airport": "Budapest Liszt Ferenc",
  "difficulty": "red",
  "altitudeSide": "redBlack",
  "modules": [
   "traffic",
   "turns",
   "winds"
  ],
  "abilityCards": 2,
  "startFeet": 5000,
  "promo": true
 },
 {
  "id": "cdg-red",
  "trackId": "cdg-red",
  "code": "CDG",
  "airport": "Paris-Charles de Gaulle",
  "difficulty": "red",
  "altitudeSide": "redBlack",
  "modules": [
   "traffic",
   "turns",
   "kerosene",
   "winds",
   "intern"
  ],
  "abilityCards": 0,
  "startFeet": 6000,
  "promo": true
 },
 {
  "id": "nzir-red",
  "trackId": "nzir-red",
  "code": "NZIR",
  "airport": "Ice Runway",
  "difficulty": "red",
  "altitudeSide": "redBlack",
  "modules": [
   "traffic",
   "turns",
   "iceBrakes",
   "windsHeadon"
  ],
  "abilityCards": 1,
  "startFeet": 6000,
  "promo": true
 },
 {
  "id": "dus-black",
  "trackId": "dus-black",
  "code": "DUS",
  "airport": "Düsseldorf",
  "difficulty": "black",
  "altitudeSide": "redBlack",
  "modules": [
   "traffic",
   "turns",
   "keroseneLeak",
   "realTime"
  ],
  "abilityCards": 1,
  "startFeet": 6000,
  "promo": true
 },
 {
  "id": "lga-black",
  "trackId": "lga-black",
  "code": "LGA",
  "airport": "LaGuardia",
  "difficulty": "black",
  "altitudeSide": "redBlack",
  "modules": [
   "traffic",
   "turns",
   "kerosene",
   "iceBrakes"
  ],
  "abilityCards": 1,
  "startFeet": 6000,
  "promo": true
 },
 {
  "id": "mad-black",
  "trackId": "mad-black",
  "code": "MAD",
  "airport": "Madrid–Barajas",
  "difficulty": "black",
  "altitudeSide": "redBlack",
  "modules": [
   "traffic",
   "turns",
   "kerosene",
   "realTime"
  ],
  "abilityCards": 1,
  "startFeet": 5000,
  "promo": true
 },
 {
  "id": "nzir-black",
  "trackId": "nzir-black",
  "code": "NZIR",
  "airport": "Ice Runway",
  "difficulty": "black",
  "altitudeSide": "redBlack",
  "modules": [
   "traffic",
   "turns",
   "iceBrakes",
   "kerosene",
   "intern",
   "windsHeadon"
  ],
  "abilityCards": 0,
  "startFeet": 6000,
  "promo": true
 },
 {
  "id": "ter-black",
  "trackId": "ter-black",
  "code": "TER",
  "airport": "Lajes, Açores",
  "difficulty": "black",
  "altitudeSide": "redBlack",
  "modules": [
   "traffic",
   "turns",
   "iceBrakes",
   "engineLoss"
  ],
  "abilityCards": 1,
  "startFeet": 6000,
  "promo": true
 },
 {
  "id": "ter-black-53",
  "trackId": "ter-black-53",
  "code": "TER",
  "airport": "Lajes, Açores",
  "difficulty": "black",
  "altitudeSide": "redBlack",
  "modules": [
   "traffic",
   "turns",
   "iceBrakes",
   "engineLoss"
  ],
  "abilityCards": 1,
  "startFeet": 6000,
  "promo": true
 }
]
